# Generated by Django 5.1.7 on 2025-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lora_details',
            name='last_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lora_details',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
