# Generated by Django 5.1.7 on 2025-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lora', '0003_lora_details_rssi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=10)),
            ],
        ),
    ]
