# Generated by Django 5.1.7 on 2025-03-21 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lora', '0006_alter_esp32mapping_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lora_details',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
