# Generated by Django 5.2 on 2025-04-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lora', '0008_lora_details_packet_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esp32mapping',
            options={'verbose_name': 'ESP32 Mapping', 'verbose_name_plural': 'ESP32 Mappings'},
        ),
        migrations.AlterModelOptions(
            name='lora_details',
            options={'verbose_name': 'LoRa Device', 'verbose_name_plural': 'LoRa Devices'},
        ),
    ]
