# Generated by Django 5.2 on 2025-04-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lora', '0009_alter_esp32mapping_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esp32mapping',
            options={'verbose_name': 'Vehicle Infomation', 'verbose_name_plural': 'Vehicle Infomation'},
        ),
        migrations.AlterModelOptions(
            name='lora_details',
            options={'verbose_name': 'GPS Information', 'verbose_name_plural': 'GPS Information'},
        ),
    ]
