# Generated by Django 5.1.4 on 2025-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lora_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('satellite', models.IntegerField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('plate_number', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
