# Generated by Django 5.1.7 on 2025-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0004_esp32mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32mapping',
            name='plate_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
