# Generated by Django 5.1.7 on 2025-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0005_alter_esp32mapping_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32mapping',
            name='identifier',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='esp32mapping',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='esp32mapping',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
