# Generated by Django 5.1.7 on 2025-04-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0007_lora_details_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lora_details',
            name='packet_number',
            field=models.IntegerField(null=True),
        ),
    ]
